### ISSUE TITLE
Error on composer require

### ISSUE THREAD

**Issue by grigdodon** [christoph-kluge/bref-sqs-laravel#1]
Hey @christoph-kluge. Thanks for the solution. 
However, there is an error when doing `composer require christoph-kluge/bref-sqs-laravel`

`@php artisan package:discover --ansi`
`Unresolvable dependency resolving [Parameter #3 [ <required> callable $isDownForMaintenance ]] in class Illuminate\Queue\Worker {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Unresolvable dependency resolving [Parameter #3 [ <required> callable $isDownForMaintenance ]] in class Illuminate\\Queue\\Worker at /home/vagrant/Code/web-dashboard/vendor/laravel/framework/src/Illuminate/Container/Container.php:993)`

**Comment by christoph-kluge** [comment]
@grigdodon could you tell me which laravel version are you using??

**Comment by grigdodon** [comment]
@christoph-kluge `"laravel/framework": "^6.2"`

**Comment by christoph-kluge** [comment]
@grigdodon the WorkCommand and the Worker changed their depndencies. I've added a branch #2 which supports laravel 5.8 and 6.x installations. 

A quick CLI test seems to work for both versions. 

I'm e2e test a 5.8+ installation now. May I ask you to validate that 6.x is working for you?

**Comment by christoph-kluge** [comment]
Seems that the 5.8.x installations are still working fine. 

<img width="1654" alt="Screenshot 2020-01-14 at 14 48 12" src="https://user-images.githubusercontent.com/1446269/72349525-f804f180-36dc-11ea-89bf-b9776455818b.png">

**Comment by grigdodon** [comment]
@christoph-kluge Laravel 6.2.x is working good with the branch you created. All good!
Thanks a lot!!

**Comment by christoph-kluge** [comment]
I'm going to merge it now 👍 

I was waiting for some feedback if it works and I'm alsp happy that you liked it! Thanks for your support.

**Comment by christoph-kluge** [comment]
Closing since #2 is merged.
