### ISSUE TITLE
Error when running on AWS

### ISSUE THREAD

**Issue by Sh1d0w** [christoph-kluge/bref-sqs-laravel#3]
Hey, first of all thanks for the package.

I am using it to run workers with Bref on AWS, however my queue is getting the following errors in cloud watch:

```
[2020-01-28 08:45:16] local.ERROR: Error executing "DeleteMessage" on "https://sqs.us-east-1.amazonaws.com/your-account-id/sqs/your-queue-name"; AWS HTTP error: Client error: `POST https://sqs.us-east-1.amazonaws.com/your-account-id/sqs/your-queue-name` resulted in a `403 Forbidden` response:
```

All my env variables are in place, if I dump $_SERVER and $_ENV in my job that is run, they are all there.

The error seems to be caused when the job is finished and SqsJob tries to remove the meesage from the queue.

I think it is  related to `SqsWorkCommand` in your package, but I haven't had the change to debug it further.

**Comment by christoph-kluge** [comment]
Hi @Sh1d0w, thank you for using/trying it out! ❤️ 

Let me quickly ask the most obvious thingy: Did you checked your credentials if you're able to perform the sqs:DeleteMessage action? 

Currently I'm using `AmazonSQSFullAccess` policy.

**Comment by Sh1d0w** [comment]
Hey thanks for the quick response. I've figured it out, the permissions was one thing, the main problem was that the queue url was incorrect.

It was my mistake that I ran the wrong queue that I have not configured.

Thanks again for the great package!
